---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-autoscaling-mercari-com-v1alpha1-tortoise
  failurePolicy: Fail
  name: mtortoise.kb.io
  rules:
  - apiGroups:
    - autoscaling.mercari.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tortoises
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-autoscaling-v2-horizontalpodautoscaler
  failurePolicy: Fail
  name: mhorizontalpodautoscaler.kb.io
  rules:
  - apiGroups:
    - autoscaling
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - horizontalpodautoscalers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-autoscaling-mercari-com-v1alpha1-tortoise
  failurePolicy: Fail
  name: vtortoise.kb.io
  rules:
  - apiGroups:
    - autoscaling.mercari.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tortoises
  sideEffects: None
