apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tortoise-serving-cert
  namespace: tortoise-system
spec:
  dnsNames:
  - tortoise-webhook-service.tortoise-system.svc
  - tortoise-webhook-service.tortoise-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: tortoise-selfsigned-issuer
  secretName: webhook-server-cert
