//go:build !ignore_autogenerated

/*
MIT License

Copyright (c) 2023 mercari

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Conditions) DeepCopyInto(out *Conditions) {
	*out = *in
	if in.TortoiseConditions != nil {
		in, out := &in.TortoiseConditions, &out.TortoiseConditions
		*out = make([]TortoiseCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ContainerRecommendationFromVPA != nil {
		in, out := &in.ContainerRecommendationFromVPA, &out.ContainerRecommendationFromVPA
		*out = make([]ContainerRecommendationFromVPA, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Conditions.
func (in *Conditions) DeepCopy() *Conditions {
	if in == nil {
		return nil
	}
	out := new(Conditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRecommendationFromVPA) DeepCopyInto(out *ContainerRecommendationFromVPA) {
	*out = *in
	if in.MaxRecommendation != nil {
		in, out := &in.MaxRecommendation, &out.MaxRecommendation
		*out = make(map[v1.ResourceName]ResourceQuantity, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Recommendation != nil {
		in, out := &in.Recommendation, &out.Recommendation
		*out = make(map[v1.ResourceName]ResourceQuantity, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRecommendationFromVPA.
func (in *ContainerRecommendationFromVPA) DeepCopy() *ContainerRecommendationFromVPA {
	if in == nil {
		return nil
	}
	out := new(ContainerRecommendationFromVPA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourcePhases) DeepCopyInto(out *ContainerResourcePhases) {
	*out = *in
	if in.ResourceePhases != nil {
		in, out := &in.ResourceePhases, &out.ResourceePhases
		*out = make(map[v1.ResourceName]ContainerResourcePhase, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourcePhases.
func (in *ContainerResourcePhases) DeepCopy() *ContainerResourcePhases {
	if in == nil {
		return nil
	}
	out := new(ContainerResourcePhases)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourcePolicy) DeepCopyInto(out *ContainerResourcePolicy) {
	*out = *in
	if in.MinAllocatedResources != nil {
		in, out := &in.MinAllocatedResources, &out.MinAllocatedResources
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.AutoscalingPolicy != nil {
		in, out := &in.AutoscalingPolicy, &out.AutoscalingPolicy
		*out = make(map[v1.ResourceName]AutoscalingType, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourcePolicy.
func (in *ContainerResourcePolicy) DeepCopy() *ContainerResourcePolicy {
	if in == nil {
		return nil
	}
	out := new(ContainerResourcePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossVersionObjectReference) DeepCopyInto(out *CrossVersionObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossVersionObjectReference.
func (in *CrossVersionObjectReference) DeepCopy() *CrossVersionObjectReference {
	if in == nil {
		return nil
	}
	out := new(CrossVersionObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HPATargetUtilizationRecommendationPerContainer) DeepCopyInto(out *HPATargetUtilizationRecommendationPerContainer) {
	*out = *in
	if in.TargetUtilization != nil {
		in, out := &in.TargetUtilization, &out.TargetUtilization
		*out = make(map[v1.ResourceName]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HPATargetUtilizationRecommendationPerContainer.
func (in *HPATargetUtilizationRecommendationPerContainer) DeepCopy() *HPATargetUtilizationRecommendationPerContainer {
	if in == nil {
		return nil
	}
	out := new(HPATargetUtilizationRecommendationPerContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalRecommendations) DeepCopyInto(out *HorizontalRecommendations) {
	*out = *in
	if in.TargetUtilizations != nil {
		in, out := &in.TargetUtilizations, &out.TargetUtilizations
		*out = make([]HPATargetUtilizationRecommendationPerContainer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = make([]ReplicasRecommendation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = make([]ReplicasRecommendation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalRecommendations.
func (in *HorizontalRecommendations) DeepCopy() *HorizontalRecommendations {
	if in == nil {
		return nil
	}
	out := new(HorizontalRecommendations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Recommendations) DeepCopyInto(out *Recommendations) {
	*out = *in
	in.Horizontal.DeepCopyInto(&out.Horizontal)
	in.Vertical.DeepCopyInto(&out.Vertical)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Recommendations.
func (in *Recommendations) DeepCopy() *Recommendations {
	if in == nil {
		return nil
	}
	out := new(Recommendations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecommendedContainerResources) DeepCopyInto(out *RecommendedContainerResources) {
	*out = *in
	if in.RecommendedResource != nil {
		in, out := &in.RecommendedResource, &out.RecommendedResource
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecommendedContainerResources.
func (in *RecommendedContainerResources) DeepCopy() *RecommendedContainerResources {
	if in == nil {
		return nil
	}
	out := new(RecommendedContainerResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicasRecommendation) DeepCopyInto(out *ReplicasRecommendation) {
	*out = *in
	if in.WeekDay != nil {
		in, out := &in.WeekDay, &out.WeekDay
		*out = new(string)
		**out = **in
	}
	in.UpdatedAt.DeepCopyInto(&out.UpdatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicasRecommendation.
func (in *ReplicasRecommendation) DeepCopy() *ReplicasRecommendation {
	if in == nil {
		return nil
	}
	out := new(ReplicasRecommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuantity) DeepCopyInto(out *ResourceQuantity) {
	*out = *in
	out.Quantity = in.Quantity.DeepCopy()
	in.UpdatedAt.DeepCopyInto(&out.UpdatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuantity.
func (in *ResourceQuantity) DeepCopy() *ResourceQuantity {
	if in == nil {
		return nil
	}
	out := new(ResourceQuantity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRefs) DeepCopyInto(out *TargetRefs) {
	*out = *in
	out.ScaleTargetRef = in.ScaleTargetRef
	if in.HorizontalPodAutoscalerName != nil {
		in, out := &in.HorizontalPodAutoscalerName, &out.HorizontalPodAutoscalerName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRefs.
func (in *TargetRefs) DeepCopy() *TargetRefs {
	if in == nil {
		return nil
	}
	out := new(TargetRefs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetStatusVerticalPodAutoscaler) DeepCopyInto(out *TargetStatusVerticalPodAutoscaler) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetStatusVerticalPodAutoscaler.
func (in *TargetStatusVerticalPodAutoscaler) DeepCopy() *TargetStatusVerticalPodAutoscaler {
	if in == nil {
		return nil
	}
	out := new(TargetStatusVerticalPodAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetsStatus) DeepCopyInto(out *TargetsStatus) {
	*out = *in
	if in.VerticalPodAutoscalers != nil {
		in, out := &in.VerticalPodAutoscalers, &out.VerticalPodAutoscalers
		*out = make([]TargetStatusVerticalPodAutoscaler, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetsStatus.
func (in *TargetsStatus) DeepCopy() *TargetsStatus {
	if in == nil {
		return nil
	}
	out := new(TargetsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tortoise) DeepCopyInto(out *Tortoise) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tortoise.
func (in *Tortoise) DeepCopy() *Tortoise {
	if in == nil {
		return nil
	}
	out := new(Tortoise)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tortoise) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TortoiseCondition) DeepCopyInto(out *TortoiseCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TortoiseCondition.
func (in *TortoiseCondition) DeepCopy() *TortoiseCondition {
	if in == nil {
		return nil
	}
	out := new(TortoiseCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TortoiseList) DeepCopyInto(out *TortoiseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tortoise, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TortoiseList.
func (in *TortoiseList) DeepCopy() *TortoiseList {
	if in == nil {
		return nil
	}
	out := new(TortoiseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TortoiseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TortoiseSpec) DeepCopyInto(out *TortoiseSpec) {
	*out = *in
	in.TargetRefs.DeepCopyInto(&out.TargetRefs)
	if in.ResourcePolicy != nil {
		in, out := &in.ResourcePolicy, &out.ResourcePolicy
		*out = make([]ContainerResourcePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TortoiseSpec.
func (in *TortoiseSpec) DeepCopy() *TortoiseSpec {
	if in == nil {
		return nil
	}
	out := new(TortoiseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TortoiseStatus) DeepCopyInto(out *TortoiseStatus) {
	*out = *in
	in.Conditions.DeepCopyInto(&out.Conditions)
	in.Recommendations.DeepCopyInto(&out.Recommendations)
	in.Targets.DeepCopyInto(&out.Targets)
	if in.ContainerResourcePhases != nil {
		in, out := &in.ContainerResourcePhases, &out.ContainerResourcePhases
		*out = make([]ContainerResourcePhases, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TortoiseStatus.
func (in *TortoiseStatus) DeepCopy() *TortoiseStatus {
	if in == nil {
		return nil
	}
	out := new(TortoiseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalRecommendations) DeepCopyInto(out *VerticalRecommendations) {
	*out = *in
	if in.ContainerResourceRecommendation != nil {
		in, out := &in.ContainerResourceRecommendation, &out.ContainerResourceRecommendation
		*out = make([]RecommendedContainerResources, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalRecommendations.
func (in *VerticalRecommendations) DeepCopy() *VerticalRecommendations {
	if in == nil {
		return nil
	}
	out := new(VerticalRecommendations)
	in.DeepCopyInto(out)
	return out
}
