name: manifests-up-to-date

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - 'docs/**'

jobs:
  manifests-up-to-date:
    name: Manifests up-to-date check
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v3.5.0
        with:
          go-version: "1.20"
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache@v3.0.10
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Get dependencies
        run: |
          go mod download
      - name: Generate
        run: make manifests
      - name: Check diff
        run: git diff --exit-code -- config
